// Socket.IO cleanup returns the socket instance, while React cleanup returns void.
// @ts-nocheck
"use client";
import { DEMO_TOPIC, DEMO_CODE } from "@/lib/demo-content";
import { useCallback, useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import dynamic from "next/dynamic";
import Editor from "@monaco-editor/react";
import { SignInPanel, useAuthSession } from "@/components/auth-session";
import type { CanvasCursor, CanvasShape } from "@/components/konva-board";
import { io, type Socket } from "socket.io-client";
import "./canvas-page.css";
const KonvaBoard=dynamic(()=>import("@/components/konva-board"),{ssr:false,loading:()=> <section className="result"><p>Loading canvas…</p></section>});
type Kind="note"|"geometry"|"code";
export default function CanvasPage(){
  const params=useSearchParams();const workspaceKey=`lesson-${(params.get("workspace")??"class-main").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,70)||"class-main"}`;const topic=params.get("topic")??DEMO_TOPIC;
  const {idToken,loading,apiFetch}=useAuthSession();const socket=useRef<Socket|null>(null);const cursorTimer=useRef<Record<string,number>>({});const [kind,setKind]=useState<Kind>("note"),[object,setObject]=useState("empty workspace"),[answer,setAnswer]=useState(""),[sharedShapes,setSharedShapes]=useState<CanvasShape[]|null>(null),[liveStatus,setLiveStatus]=useState("Connecting shared workspace…"),[collaborators,setCollaborators]=useState<Array<{id:string;displayName:string;role:string}>>([]),[remoteCursors,setRemoteCursors]=useState<CanvasCursor[]>([]);const [content,setContent]=useState("Select a drawing, note, geometry object, or code snippet and ask for help."),[code,setCode]=useState(DEMO_CODE),[language,setLanguage]=useState("typescript");
  useEffect(()=>{setContent(`Topic workspace: ${topic}. Use the Canvas to draw the important reasoning steps, then ask for a note-grounded explanation.`);setObject(topic);},[topic]);
  async function ask(){const prompt=`Learning Canvas ${kind} context: ${content}. Latest object: ${object}.${kind==="code"?`\n${language} code:\n${code}`:""}\nUse my authorized course notes, identify a likely mistake, and suggest one practice question.`;const response=await apiFetch("/api/orchestrate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query:prompt})});const body=await response.json();setAnswer(response.ok?body.answer:body.error);}
  useEffect(()=>{if(!idToken)return;setSharedShapes(null);void apiFetch(`/api/canvas/shared?classId=cn-b&workspaceKey=${encodeURIComponent(workspaceKey)}`).then(async response=>{const body=await response.json();setSharedShapes(response.ok&&Array.isArray(body.state)?body.state:[]);}).catch(()=>setSharedShapes([]));},[idToken,apiFetch,workspaceKey]);
  useEffect(()=>{if(!idToken)return;const client=io(process.env.NEXT_PUBLIC_REALTIME_URL??"http://localhost:3003",{auth:{token:idToken},reconnectionAttempts:3,timeout:5000});socket.current=client;client.on("connect",()=>{setLiveStatus("Live collaboration connected");client.emit("canvas:join",{classId:"cn-b",workspaceKey});});client.on("connect_error",()=>setLiveStatus("Live collaboration unavailable"));client.on("canvas:state",({state,updatedBy}:{state:unknown;updatedBy:string})=>{if(Array.isArray(state)){setSharedShapes(state as CanvasShape[]);setLiveStatus(`Updated live by ${updatedBy}`);}});client.on("canvas:presence",({participants}:{participants:Array<{id:string;displayName:string;role:string}>})=>setCollaborators(Array.isArray(participants)?participants:[]));client.on("canvas:cursor",(cursor:CanvasCursor)=>{if(!cursor?.id)return;setRemoteCursors(current=>[...current.filter(item=>item.id!==cursor.id),cursor]);window.clearTimeout(cursorTimer.current[cursor.id]);cursorTimer.current[cursor.id]=window.setTimeout(()=>setRemoteCursors(current=>current.filter(item=>item.id!==cursor.id)),2500);});return()=>{Object.values(cursorTimer.current).forEach(window.clearTimeout);client.disconnect();};},[idToken,workspaceKey]);
  const persist=useCallback(async(shapes:CanvasShape[])=>{const response=await apiFetch("/api/canvas/shared",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({classId:"cn-b",workspaceKey,state:shapes})});if(!response.ok)throw new Error("Could not save shared canvas");},[apiFetch,workspaceKey]);
  const liveChange=useCallback((shapes:CanvasShape[])=>socket.current?.emit("canvas:state",{classId:"cn-b",workspaceKey,state:shapes}),[workspaceKey]);
  const suggestion=(value:string)=>setContent(value.replace("{topic}",topic));
  if(loading)return <main><p>Checking sign-in session…</p></main>;if(!idToken)return <main><section className="hero"><h1>Learning Canvas</h1></section><SignInPanel/></main>;
  return <main className="canvas-page">
    <section className="canvas-hero"><div className="canvas-hero-copy"><span className="eyebrow">LESSON-SPECIFIC LEARNING CANVAS</span><h1>Draw, code, reason,<br/>then ask AI.</h1><p>This canvas belongs only to the current lesson workspace, with its own saved drawings.</p><small>{liveStatus} · {collaborators.length ? `${collaborators.length} collaborator${collaborators.length===1?"":"s"}: ${collaborators.map(item=>item.displayName).join(", ")}` : "Only you can view"}</small></div><div className="canvas-hero-pattern" aria-hidden="true">{Array.from({length:20}).map((_,i)=><i key={i}/>)}</div></section>
    {sharedShapes===null?<section className="result"><p>Loading lesson Canvas…</p></section>:<KonvaBoard onChange={setObject} initialShapes={sharedShapes} onPersist={persist} onLiveChange={liveChange} onCursorMove={({x,y})=>socket.current?.emit("canvas:cursor",{classId:"cn-b",workspaceKey,x,y})} remoteCursors={remoteCursors} collaborators={collaborators}/>} 
    <section className="canvas-ai-panel"><div className="canvas-mode-tabs"><button className={kind==="note"?"active":""} onClick={()=>setKind("note")}>▤ &nbsp; Note</button><button className={kind==="geometry"?"active":""} onClick={()=>setKind("geometry")}>△ &nbsp; Geometry</button><button className={kind==="code"?"active":""} onClick={()=>setKind("code")}>‹/› &nbsp; Code</button></div>{kind==="code"&&<><label htmlFor="code-language">Language</label><select id="code-language" value={language} onChange={event=>setLanguage(event.target.value)}><option value="typescript">TypeScript</option><option value="javascript">JavaScript</option><option value="python">Python</option><option value="cpp">C++</option></select><label>Code workspace</label><div className="monaco-shell"><Editor height="360px" language={language} theme="vs-dark" value={code} onChange={value=>setCode(value??"")} options={{minimap:{enabled:false},fontSize:15,automaticLayout:true}}/></div></>}<label>Selected {kind} context</label><textarea maxLength={2000} rows={6} value={content} onChange={event=>setContent(event.target.value)}/><span className="canvas-context-count">{content.length}/2000</span><div className="canvas-ask-row"><button onClick={()=>void ask()}>✦ &nbsp; Ask ShikshaMesh &nbsp; →</button><div className="canvas-suggestions"><span>Try asking:</span><button onClick={()=>suggestion("Explain this diagram using my notes for {topic}.")}>Explain this diagram</button><button onClick={()=>suggestion("Find mistakes in my reasoning for {topic} and explain how to fix them.")}>Find mistakes</button><button onClick={()=>suggestion("Turn this canvas into concise revision notes for {topic}.")}>Turn this into notes</button></div></div>{answer&&<p className="canvas-answer">{answer}</p>}</section>
  </main>;
}

export default function CanvasPage() {
  return <Suspense fallback={<main><p>Loading canvas…</p></main>}><CanvasPageContent /></Suspense>;
}
