"use client";

import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { SignInPanel, useAuthSession } from "@/components/auth-session";
import { MermaidDiagram } from "@/components/mermaid-diagram";

type Kind = "flowchart" | "sequence" | "class" | "state" | "er";
type Template = { label: string; kind: Kind; make: (topic: string) => string };
const templates: Template[] = [
  { label: "Learning flow", kind: "flowchart", make: topic => `flowchart LR\n  A[Read ${topic}] --> B[Identify core idea]\n  B --> C[Work an example]\n  C --> D[Explain it back]` },
  { label: "UML class", kind: "class", make: topic => `classDiagram\n  class ${topic.replace(/[^a-z0-9]/gi, "") || "Concept"} {\n    +definition\n    +solveExample()\n  }\n  class Student {\n    +practice()\n  }\n  Student --> ${topic.replace(/[^a-z0-9]/gi, "") || "Concept"} : learns` },
  { label: "UML sequence", kind: "sequence", make: topic => `sequenceDiagram\n  participant Student\n  participant Tutor\n  participant Notes\n  Student->>Tutor: Ask about ${topic}\n  Tutor->>Notes: Retrieve relevant concepts\n  Notes-->>Tutor: Grounded explanation\n  Tutor-->>Student: Example and practice` },
  { label: "Database schema", kind: "er", make: topic => `erDiagram\n  STUDENT ||--o{ ATTEMPT : makes\n  CONCEPT ||--o{ ATTEMPT : evaluates\n  CONCEPT {\n    string title "${topic}"\n  }\n  ATTEMPT {\n    number score\n  }` },
  { label: "DSA decision tree", kind: "flowchart", make: topic => `flowchart TD\n  A[Problem: ${topic}] --> B{What is the invariant?}\n  B --> C[Precompute useful state]\n  C --> D[Answer each query]\n  D --> E[Check edge cases]` },
];

function DiagramsPageContent() {
  const params = useSearchParams(); const { idToken, loading, apiFetch } = useAuthSession();
  const workspace = (params.get("workspace") ?? "class-main").replace(/[^a-zA-Z0-9_-]/g, "").slice(0, 70) || "class-main";
  const workspaceKey = `lesson-${workspace}`;
  const [topic, setTopic] = useState(() => params.get("topic") ?? "Binary Lifting"); const [kind, setKind] = useState<Kind>("flowchart");
  const [code, setCode] = useState(templates[0].make(params.get("topic") ?? "Binary Lifting")); const [submitted, setSubmitted] = useState(code);
  const [status, setStatus] = useState("Choose a classroom template, edit it, or generate from your approved notes."); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(()=>{const templateId=params.get("template")??params.get("topic");if(!idToken||!templateId)return;void apiFetch("/api/teacher/diagram-templates?classId=cn-b").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error??"Unable to load class template");const template=(body.templates??[]).find((item:{id:string;title:string})=>item.id===templateId||item.title===templateId);if(!template)return;setTopic(template.title);setKind(template.kind);setCode(template.code);setSubmitted(template.code);setStatus(`Loaded class template: ${template.title}`);}).catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load class template"));},[idToken,apiFetch,params]);
  function useTemplate(index: number) { const template = templates[index]; const next = template.make(topic || "Untitled concept"); setKind(template.kind); setCode(next); setSubmitted(next); setStatus(`${template.label} template loaded. Edit it or publish it to the lesson Canvas.`); }
  async function generate() { setBusy(true); setError(""); try { const response = await apiFetch("/api/diagrams", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ classId: "cn-b", topic, kind }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to generate diagram"); setCode(body.code); setSubmitted(body.code); setStatus(`Generated with ${body.provider} · ${body.sources.length} authorized note source(s)`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to generate diagram"); } finally { setBusy(false); } }
  async function publishToCanvas() { setBusy(true); setError(""); try { const load = await apiFetch(`/api/canvas/shared?classId=cn-b&workspaceKey=${encodeURIComponent(workspaceKey)}`); const existing = await load.json(); if (!load.ok) throw new Error(existing.error ?? "Could not load the shared Canvas"); const state = [...(Array.isArray(existing.state) ? existing.state : []), { id: crypto.randomUUID(), type: "note", x: 90, y: 90, text: `DIAGRAM · ${topic || "Untitled"}\n${submitted.slice(0, 1200)}` }]; const save = await apiFetch("/api/canvas/shared", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ classId: "cn-b", workspaceKey, state }) }); const body = await save.json(); if (!save.ok) throw new Error(body.error ?? "Could not publish to Canvas"); setStatus("Diagram published to the shared lesson Canvas. Open Canvas to arrange, annotate, and connect it."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not publish to Canvas"); } finally { setBusy(false); } }
  if (loading) return <main><p>Checking sign-in session…</p></main>;
  if (!idToken) return <main><section className="hero"><span className="eyebrow">VISUAL LEARNING</span><h1>Diagram Studio</h1><p>Build and explain flowcharts from your course material.</p></section><SignInPanel /></main>;
  return <main className="diagram-page"><section className="hero"><span className="eyebrow">MERMAID · NOTE-GROUNDED VISUALS</span><h1>Turn a topic into a diagram.</h1><p>Use a ready classroom template, generate from authorized notes, then publish it into the shared lesson workspace.</p></section><section className="diagram-studio"><aside className="diagram-controls"><label htmlFor="diagram-template">Quick classroom template</label><select id="diagram-template" defaultValue="" onChange={event => event.target.value && useTemplate(Number(event.target.value))}><option value="" disabled>Choose a template</option>{templates.map((template, index) => <option value={index} key={template.label}>{template.label}</option>)}</select><label htmlFor="diagram-topic">Topic</label><input id="diagram-topic" value={topic} onChange={event => setTopic(event.target.value)} /><label htmlFor="diagram-kind">Diagram type</label><select id="diagram-kind" value={kind} onChange={event => setKind(event.target.value as Kind)}><option value="flowchart">Flowchart</option><option value="sequence">UML sequence diagram</option><option value="class">UML class diagram</option><option value="state">State machine</option><option value="er">Entity relationship diagram</option></select><button type="button" onClick={() => void generate()} disabled={busy}>{busy ? "Working…" : "Generate from notes"}</button><label htmlFor="mermaid-code">Mermaid code</label><textarea id="mermaid-code" rows={18} spellCheck={false} value={code} onChange={event => setCode(event.target.value)} /><button type="button" className="diagram-preview-button" onClick={() => { setSubmitted(code); setStatus("Preview updated from your Mermaid code."); }}>Update preview</button></aside><section className="diagram-preview"><div className="diagram-preview-head"><div><span className="eyebrow">LIVE PREVIEW</span><h2>{topic || "Untitled diagram"}</h2></div><div className="diagram-actions"><button type="button" onClick={() => navigator.clipboard.writeText(submitted)}>Copy code</button><button type="button" className="diagram-publish" onClick={() => void publishToCanvas()} disabled={busy}>Publish to Canvas</button></div></div><MermaidDiagram code={submitted} /><small>{status}</small><p className="diagram-canvas-hint">This publishes to this lesson’s shared board. <a href={`/canvas?topic=${encodeURIComponent(topic)}&workspace=${encodeURIComponent(workspace)}`}>Open Canvas</a></p>{error && <p className="error">{error}</p>}</section></section></main>;
}

export default function DiagramsPage() {
  return <Suspense fallback={<main><p>Loading Diagram Studio…</p></main>}><DiagramsPageContent /></Suspense>;
}
