"use client";
import { DEMO_TOPIC } from "@/lib/demo-content";
import { FormEvent, useState } from "react";
import { SignInPanel, useAuthSession } from "@/components/auth-session";
type Result = { title: string; url: string; snippet: string }; type Purpose = "curriculum" | "prerequisites" | "safety" | "practice";
export default function OfficialResourcesPage() {
  const { idToken, loading, apiFetch } = useAuthSession(); const [topic, setTopic] = useState(DEMO_TOPIC + " relational database design"); const [purpose, setPurpose] = useState<Purpose>("curriculum"); const [results, setResults] = useState<Result[]>([]); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  async function search(event: FormEvent) { event.preventDefault(); setBusy(true); setStatus(""); try { const response = await apiFetch("/api/research/official-resources", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ topic, purpose }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Search unavailable"); setResults(body.results); setStatus(body.results.length ? "Official sources found through SerpAPI." : "No approved sources found. Check the topic or configured domain allowlist."); } catch (error) { setResults([]); setStatus(error instanceof Error ? error.message : "Search unavailable"); } finally { setBusy(false); } }
  if (loading) return <main><p>Checking sign-in session…</p></main>;
  if (!idToken) return <main><section className="hero"><span className="eyebrow">OFFICIAL RESOURCES</span><h1>Sign in to find verified learning material.</h1></section><SignInPanel /></main>;
  return <main className="resources-page"><section className="policy-hero"><span className="eyebrow">OFFICIAL RESOURCE FINDER</span><h1>Find trusted material around your notes.</h1><p>Searches only your administrator-approved domains through SerpAPI. Results support learning; they never replace uploaded course evidence.</p></section><form className="composer resource-form" onSubmit={search}><label htmlFor="resource-topic">Topic or concept</label><input id="resource-topic" value={topic} onChange={event => setTopic(event.target.value)} placeholder="e.g. library catalog, database transactions, role-based access" required /><label htmlFor="resource-purpose">What do you need?</label><select id="resource-purpose" value={purpose} onChange={event => setPurpose(event.target.value as Purpose)}><option value="curriculum">Official syllabus or learning outcomes</option><option value="prerequisites">Prerequisites and foundations</option><option value="safety">Safety guidance or advisory</option><option value="practice">Official examples or practice material</option></select><button disabled={busy}>{busy ? "Searching approved sources…" : "Find official resources"}</button></form>{status && <p className={results.length ? "form-success" : "notice"}>{status}</p>}{results.length > 0 && <section className="resource-results"><span className="eyebrow">SUPPLEMENTARY EVIDENCE</span>{results.map(result => <article key={result.url}><h2><a href={result.url} target="_blank" rel="noreferrer">{result.title}</a></h2><p>{result.snippet}</p><small>{new URL(result.url).hostname}</small></article>)}</section>}</main>;
}
