"use client";

import { ChangePasswordCommand, CognitoIdentityProviderClient, ConfirmForgotPasswordCommand, ConfirmSignUpCommand, ForgotPasswordCommand, InitiateAuthCommand, ResendConfirmationCodeCommand, SignUpCommand } from "@aws-sdk/client-cognito-identity-provider";
import { createContext, FormEvent, ReactNode, useContext, useEffect, useMemo, useState } from "react";
import styles from "./auth-session.module.css";

type AuthRole = "student" | "teacher" | "admin";
type AuthContextValue = { idToken: string | null; role: AuthRole; loading: boolean; apiFetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>; changePassword: (currentPassword: string, newPassword: string) => Promise<void>; signOut: () => void };
type Mode = "sign-in" | "sign-up" | "confirm" | "forgot" | "reset";
const AuthContext = createContext<AuthContextValue | undefined>(undefined);
const idTokenKey = "shikshamesh.cognito.id-token"; const accessTokenKey = "shikshamesh.cognito.access-token";
function roleFromToken(token: string | null): AuthRole {
  if (!token) return "student";
  try {
    const encodedPayload = token.split(".")[1].replaceAll("-", "+").replaceAll("_", "/");
    const payload = JSON.parse(atob(encodedPayload.padEnd(Math.ceil(encodedPayload.length / 4) * 4, "="))) as { [key: string]: unknown };
    const groups = Array.isArray(payload["cognito:groups"]) ? payload["cognito:groups"] : [];
    if (groups.includes("admin")) return "admin";
    if (groups.includes("teacher")) return "teacher";
  } catch {
  }
  return "student";
}
function configuration() { const region = process.env.NEXT_PUBLIC_AWS_REGION; const clientId = process.env.NEXT_PUBLIC_COGNITO_APP_CLIENT_ID; if (!region || !clientId) throw new Error("Cognito browser configuration is unavailable"); return { region, clientId }; }
function cognito() { return new CognitoIdentityProviderClient({ region: configuration().region }); }

export function AuthSessionProvider({ children }: { children: ReactNode }) {
  const [idToken, setIdToken] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { setIdToken(sessionStorage.getItem(idTokenKey)); setLoading(false); }, []);
  const value = useMemo<AuthContextValue>(() => ({ idToken, role: roleFromToken(idToken), loading, apiFetch: (input, init = {}) => fetch(input, { ...init, headers: { ...init.headers, ...(idToken ? { authorization: `Bearer ${idToken}` } : {}) } }), changePassword: async (previousPassword, proposedPassword) => { const accessToken = sessionStorage.getItem(accessTokenKey); if (!accessToken) throw new Error("Please sign out and sign in again before changing your password"); await cognito().send(new ChangePasswordCommand({ AccessToken: accessToken, PreviousPassword: previousPassword, ProposedPassword: proposedPassword })); }, signOut: () => { sessionStorage.removeItem(idTokenKey); sessionStorage.removeItem(accessTokenKey); setIdToken(null); } }), [idToken, loading]);
  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}
export function useAuthSession() { const value = useContext(AuthContext); if (!value) throw new Error("useAuthSession must be used inside AuthSessionProvider"); return value; }

export function SignInPanel() {
  const { idToken, loading, signOut } = useAuthSession(); const [mode, setMode] = useState<Mode>("sign-in"); const [username, setUsername] = useState(""); const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [code, setCode] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [submitting, setSubmitting] = useState(false);
  const clear = () => { setError(""); setNotice(""); }; const choose = (next: Mode) => { clear(); setMode(next); };
  async function signIn(event: FormEvent) { event.preventDefault(); clear(); setSubmitting(true); try { const { clientId } = configuration(); const result = await cognito().send(new InitiateAuthCommand({ AuthFlow: "USER_PASSWORD_AUTH", ClientId: clientId, AuthParameters: { USERNAME: username, PASSWORD: password } })); const id = result.AuthenticationResult?.IdToken; const access = result.AuthenticationResult?.AccessToken; if (!id || !access) throw new Error("Sign-in needs account confirmation or a password update."); sessionStorage.setItem(idTokenKey, id); sessionStorage.setItem(accessTokenKey, access); window.location.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Sign-in failed"); } finally { setSubmitting(false); } }
  async function signUp(event: FormEvent) { event.preventDefault(); clear(); if (password !== confirmPassword) return setError("Passwords do not match"); setSubmitting(true); try { const { clientId } = configuration(); await cognito().send(new SignUpCommand({ ClientId: clientId, Username: username, Password: password, UserAttributes: [{ Name: "email", Value: email }, ...(name ? [{ Name: "name", Value: name }] : [])] })); setPassword(""); setConfirmPassword(""); setNotice("Check your email for the confirmation code."); setMode("confirm"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create account"); } finally { setSubmitting(false); } }
  async function confirmAccount(event: FormEvent) { event.preventDefault(); clear(); setSubmitting(true); try { const { clientId } = configuration(); await cognito().send(new ConfirmSignUpCommand({ ClientId: clientId, Username: username, ConfirmationCode: code })); setCode(""); setNotice("Account confirmed. Your institution must now assign your class access."); setMode("sign-in"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not confirm account"); } finally { setSubmitting(false); } }
  async function resend() { clear(); setSubmitting(true); try { const { clientId } = configuration(); await cognito().send(new ResendConfirmationCodeCommand({ ClientId: clientId, Username: username })); setNotice("A new confirmation code was sent."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not resend confirmation code"); } finally { setSubmitting(false); } }
  async function forgot(event: FormEvent) { event.preventDefault(); clear(); setSubmitting(true); try { const { clientId } = configuration(); await cognito().send(new ForgotPasswordCommand({ ClientId: clientId, Username: username })); setNotice("If this account has a verified email or phone, Cognito sent a reset code."); setMode("reset"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not start recovery"); } finally { setSubmitting(false); } }
  async function reset(event: FormEvent) { event.preventDefault(); clear(); if (password !== confirmPassword) return setError("Passwords do not match"); setSubmitting(true); try { const { clientId } = configuration(); await cognito().send(new ConfirmForgotPasswordCommand({ ClientId: clientId, Username: username, ConfirmationCode: code, Password: password })); setPassword(""); setConfirmPassword(""); setCode(""); setNotice("Password reset. You can sign in now."); setMode("sign-in"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not reset password"); } finally { setSubmitting(false); } }
  if (loading) return <p>Checking sign-in session…</p>;
  if (idToken) return <div className="session"><span>Signed in with Cognito</span><a href="/account">Account</a><button onClick={signOut}>Sign out</button></div>;
  return <section className={`${styles.root} composer sign-in`}><span className="eyebrow">SHIKSHAMESH ACCESS</span><h2>{mode === "sign-up" ? "Create your learner account" : mode === "confirm" ? "Confirm your email" : mode === "forgot" || mode === "reset" ? "Recover your account" : "Welcome back"}</h2><p>{mode === "sign-up" ? "New accounts start as learners. Your institution assigns class access and staff roles." : "Secure learning access with Amazon Cognito."}</p>{(mode === "sign-in" || mode === "sign-up") && <div className="auth-tabs"><button type="button" className={mode === "sign-in" ? "active" : "secondary"} onClick={() => choose("sign-in")}>Sign in</button><button type="button" className={mode === "sign-up" ? "active" : "secondary"} onClick={() => choose("sign-up")}>Create account</button></div>}
    {mode === "sign-in" && <form onSubmit={signIn}><label htmlFor="username">Username</label><input id="username" autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} required /><label htmlFor="password">Password</label><input id="password" type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required /><button disabled={submitting}>{submitting ? "Signing in…" : "Sign in"}</button><button type="button" className="secondary" onClick={() => choose("forgot")}>Forgot password?</button></form>}
    {mode === "sign-up" && <form onSubmit={signUp}><label htmlFor="signup-name">Full name</label><input id="signup-name" autoComplete="name" value={name} onChange={(event) => setName(event.target.value)} /><label htmlFor="signup-email">Email</label><input id="signup-email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required /><label htmlFor="signup-username">Username</label><input id="signup-username" autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} required /><label htmlFor="signup-password">Password</label><input id="signup-password" type="password" autoComplete="new-password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} required /><label htmlFor="signup-confirm">Confirm password</label><input id="signup-confirm" type="password" autoComplete="new-password" minLength={8} value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required /><button disabled={submitting}>{submitting ? "Creating account…" : "Create learner account"}</button></form>}
    {mode === "confirm" && <form onSubmit={confirmAccount}><label htmlFor="confirm-username">Username</label><input id="confirm-username" autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} required /><label htmlFor="confirmation-code">Confirmation code</label><input id="confirmation-code" autoComplete="one-time-code" value={code} onChange={(event) => setCode(event.target.value)} required /><button disabled={submitting}>Confirm account</button><button type="button" className="secondary" disabled={submitting} onClick={resend}>Resend code</button></form>}
    {mode === "forgot" && <form onSubmit={forgot}><label htmlFor="recovery-username">Username</label><input id="recovery-username" autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} required /><button disabled={submitting}>Send reset code</button><button type="button" className="secondary" onClick={() => choose("sign-in")}>Back to sign in</button></form>}
    {mode === "reset" && <form onSubmit={reset}><label htmlFor="reset-code">Reset code</label><input id="reset-code" autoComplete="one-time-code" value={code} onChange={(event) => setCode(event.target.value)} required /><label htmlFor="reset-password">New password</label><input id="reset-password" type="password" autoComplete="new-password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} required /><label htmlFor="reset-confirm">Confirm new password</label><input id="reset-confirm" type="password" autoComplete="new-password" minLength={8} value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required /><button disabled={submitting}>Reset password</button></form>}
    {notice && <p className="notice">{notice}</p>}{error && <p className="error">{error}</p>}</section>;
}
