// The IVS SDK runs only in the browser; its event typing is more permissive than
// React's DOM types, so this component isolates that SDK boundary.
// @ts-nocheck
"use client";
import { useEffect, useRef, useState } from "react";
import { useAuthSession } from "@/components/auth-session";

export function IvsRoom(){const {apiFetch}=useAuthSession();const [camera,setCamera]=useState(false),[microphone,setMicrophone]=useState(false),[state,setState]=useState<"idle"|"joining"|"joined">("idle"),[message,setMessage]=useState("Video is off. Joining without camera or microphone is free of device permissions."),[error,setError]=useState("");const stageRef=useRef(null),mediaRef=useRef(null),localVideo=useRef(null),remoteGrid=useRef(null);
  useEffect(()=>()=>leave(),[]);
  function addRemote(stream){const track=stream.mediaStreamTrack;if(!track||!remoteGrid.current)return;const id=`remote-${stream.id}`;if(document.getElementById(id))return;const element=document.createElement(track.kind==="video"?"video":"audio");element.id=id;element.autoplay=true;element.playsInline=true;element.controls=false;element.srcObject=new MediaStream([track]);if(track.kind==="video"){element.className="ivs-video";remoteGrid.current.append(element);}else{document.body.append(element);}}
  async function join(){setError("");setState("joining");try{const wantsPublish=camera||microphone;const response=await apiFetch("/api/live/ivs-token",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({classId:"cn-b",publish:wantsPublish})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Unable to join video room");const sdk=await import("amazon-ivs-web-broadcast");let media=null,streams=[];if(wantsPublish){media=await navigator.mediaDevices.getUserMedia({video:camera?{width:{ideal:1280},height:{ideal:720}}:false,audio:microphone});mediaRef.current=media;if(localVideo.current&&camera){localVideo.current.srcObject=media;await localVideo.current.play().catch(()=>{});}streams=media.getTracks().map(track=>new sdk.LocalStageStream(track));}const strategy={stageStreamsToPublish:()=>streams,shouldPublishParticipant:()=>true,shouldSubscribeToParticipant:()=>sdk.SubscribeType.AUDIO_VIDEO};const stage=new sdk.Stage(body.token,strategy);stageRef.current=stage;stage.on(sdk.StageEvents.STAGE_PARTICIPANT_STREAMS_ADDED,(_participant,remoteStreams)=>remoteStreams.forEach(addRemote));stage.on(sdk.StageEvents.ERROR,event=>setError(event?.message??"IVS video connection error"));stage.on(sdk.StageEvents.STAGE_CONNECTION_STATE_CHANGED,next=>setMessage(`Video room: ${String(next).toLowerCase()}`));await stage.join();setState("joined");setMessage(wantsPublish?"You are sharing only the devices you selected.":"You joined as a viewer. Camera and microphone remain off.");}catch(reason){leave();setError(reason instanceof Error?reason.message:"Unable to join video room");setState("idle");}}
  function leave(){try{stageRef.current?.leave();}catch{}stageRef.current=null;mediaRef.current?.getTracks().forEach(track=>track.stop());mediaRef.current=null;if(localVideo.current)localVideo.current.srcObject=null;if(remoteGrid.current)remoteGrid.current.replaceChildren();setState("idle");}
  return <section className="ivs-room"><div className="ivs-head"><div><span className="eyebrow">OPTIONAL WEBRTC VIDEO</span><h2>Interactive video room</h2><p>{message}</p></div><span className={state==="joined"?"ivs-badge live":"ivs-badge"}>{state==="joined"?"LIVE":"VIDEO OFF"}</span></div>{state!=="joined"?<div className="ivs-lobby"><div><b>Choose what to share</b><label className="ivs-toggle"><input type="checkbox" checked={camera} onChange={event=>setCamera(event.target.checked)}/> Camera</label><label className="ivs-toggle"><input type="checkbox" checked={microphone} onChange={event=>setMicrophone(event.target.checked)}/> Microphone</label><small>Nothing is requested from your device until you join.</small></div><button type="button" onClick={()=>void join()} disabled={state==="joining"}>{state==="joining"?"Joining secure room…":"Join video room"}</button></div>:<div className="ivs-stage"><div className="ivs-local"><span>You</span><video ref={localVideo} autoPlay muted playsInline/></div><div ref={remoteGrid} className="ivs-remotes"><p>Waiting for other video participants…</p></div><button type="button" className="ivs-leave" onClick={leave}>Leave video room</button></div>}{error&&<p className="error">{error}</p>}<small className="ivs-note">A session is limited to 45 minutes. Participant tokens are server-issued, stage-scoped, and never placed in your environment file.</small></section>;}
