// Konva's `Layer.add` declaration does not accept its shared Node base type,
// although every object created below is a Konva shape/group at runtime.
// @ts-nocheck
"use client";

import { useEffect, useRef, useState } from "react";
import Konva from "konva";

type ShapeTool = "pen" | "note" | "rectangle" | "circle";
type Tool = "select" | ShapeTool;
export type CanvasShape = { id:string; type:ShapeTool; x:number; y:number; text?:string; points?:number[]; width?:number; height?:number; radius?:number };
const BOARD_W=1100, BOARD_H=650, storageKey="shikshamesh.konva-canvas.v5";
const tools: Array<{tool:Tool;label:string;key?:string}> = [
  {tool:"select",label:"Select",key:"V"},{tool:"pen",label:"Pen",key:"P"},{tool:"note",label:"Text note",key:"T"},{tool:"rectangle",label:"Rectangle",key:"R"},{tool:"circle",label:"Circle",key:"O"},
];

export default function KonvaBoard({onChange,initialShapes=[],onPersist,onLiveChange}:{onChange:(value:string)=>void;initialShapes?:CanvasShape[];onPersist?:(value:CanvasShape[])=>Promise<void>;onLiveChange?:(value:CanvasShape[])=>void}) {
  const container=useRef<HTMLDivElement>(null),stage=useRef<Konva.Stage|null>(null),layer=useRef<Konva.Layer|null>(null),shapesRef=useRef<CanvasShape[]>([]),toolRef=useRef<Tool>("select"),drawing=useRef<string|null>(null),zoomRef=useRef(1),history=useRef<CanvasShape[][]>([]),future=useRef<CanvasShape[][]>([]),ready=useRef(false),skipSave=useRef(true);
  const [shapes,setShapes]=useState<CanvasShape[]>([]),[tool,setTool]=useState<Tool>("select"),[selected,setSelected]=useState<string|null>(null),[zoom,setZoom]=useState(1),[status,setStatus]=useState(""),[undoable,setUndoable]=useState(false),[redoable,setRedoable]=useState(false);
  const historyState=()=>{setUndoable(history.current.length>0);setRedoable(future.current.length>0);};
  function commit(next:CanvasShape[],record=true){if(record){history.current=[...history.current.slice(-49),shapesRef.current];future.current=[];historyState();}shapesRef.current=next;setShapes(next);localStorage.setItem(storageKey,JSON.stringify(next));onChange(next.at(-1)?.type??"empty workspace");onLiveChange?.(next);setStatus(navigator.onLine?"Saved locally":"Saved locally — offline mode");}
  function undo(){const previous=history.current.pop();if(!previous)return;future.current.push(shapesRef.current);historyState();commit(previous,false);setSelected(null);}
  function redo(){const next=future.current.pop();if(!next)return;history.current.push(shapesRef.current);historyState();commit(next,false);setSelected(null);}
  useEffect(()=>{const raw=localStorage.getItem(storageKey);if(raw&&!initialShapes.length){try{commit(JSON.parse(raw),false);setStatus("Restored local workspace");}catch{}}// eslint-disable-next-line react-hooks/exhaustive-deps
  },[initialShapes.length]);
  useEffect(()=>{shapesRef.current=initialShapes;setShapes(initialShapes);localStorage.setItem(storageKey,JSON.stringify(initialShapes));onChange(initialShapes.at(-1)?.type??"empty workspace");ready.current=true;skipSave.current=true;setStatus("Shared workspace loaded");},[initialShapes,onChange]);
  useEffect(()=>{if(!ready.current||!onPersist)return;if(skipSave.current){skipSave.current=false;return;}const timer=window.setTimeout(()=>void onPersist(shapes).then(()=>setStatus("Saved to shared class workspace")).catch(()=>setStatus("Saved locally — shared save will retry")),700);return()=>window.clearTimeout(timer);},[shapes,onPersist]);
  useEffect(()=>{toolRef.current=tool;},[tool]);
  useEffect(()=>{zoomRef.current=zoom;stage.current?.scale({x:zoom,y:zoom});stage.current?.batchDraw();},[zoom]);
  useEffect(()=>{if(!container.current)return;const nextStage=new Konva.Stage({container:container.current,width:BOARD_W,height:BOARD_H});const nextLayer=new Konva.Layer();nextStage.add(nextLayer);stage.current=nextStage;layer.current=nextLayer;const point=()=>{const p=nextStage.getPointerPosition();return p?{x:p.x/zoomRef.current,y:p.y/zoomRef.current}:null;};nextStage.on("mousedown touchstart",event=>{const p=point();if(!p||toolRef.current==="select"||event.target!==nextStage)return;const id=crypto.randomUUID();if(toolRef.current==="pen"){drawing.current=id;commit([...shapesRef.current,{id,type:"pen",x:0,y:0,points:[p.x,p.y]}]);return;}const item:CanvasShape=toolRef.current==="note"?{id,type:"note",x:p.x,y:p.y,text:"Double-click to edit"}:toolRef.current==="rectangle"?{id,type:"rectangle",x:p.x,y:p.y,width:190,height:110}:{id,type:"circle",x:p.x,y:p.y,radius:58};commit([...shapesRef.current,item]);setSelected(id);setTool("select");});nextStage.on("mousemove touchmove",()=>{const p=point(),id=drawing.current;if(!p||!id)return;commit(shapesRef.current.map(item=>item.id===id?{...item,points:[...(item.points??[]),p.x,p.y]}:item),false);});nextStage.on("mouseup touchend",()=>drawing.current=null);return()=>{nextStage.destroy();};// eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{const element=event.target as HTMLElement;if(["INPUT","TEXTAREA"].includes(element.tagName))return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){event.preventDefault();event.shiftKey?redo():undo();return;}if(["Delete","Backspace"].includes(event.key)&&selected){event.preventDefault();commit(shapesRef.current.filter(item=>item.id!==selected));setSelected(null);return;}const match=tools.find(item=>item.key?.toLowerCase()===event.key.toLowerCase());if(match)setTool(match.tool);};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler);});
  useEffect(()=>{const canvas=layer.current;if(!canvas)return;canvas.destroyChildren();canvas.add(new Konva.Rect({x:0,y:0,width:BOARD_W,height:BOARD_H,fill:"#f8fafc"}));canvas.add(new Konva.Line({points:[0,42,BOARD_W,42],stroke:"#e6edf5",strokeWidth:1}));for(const item of shapes){let node:Konva.Node;if(item.type==="pen"){node=new Konva.Line({points:item.points,stroke:"#172c43",strokeWidth:4,lineCap:"round",lineJoin:"round",hitStrokeWidth:18});}else if(item.type==="note"){const group=new Konva.Group({x:item.x,y:item.y,draggable:true});const text=new Konva.Text({text:item.text,fill:"#142a43",fontSize:19,fontFamily:"Inter, Arial",padding:13,width:230,lineHeight:1.25});group.add(new Konva.Rect({width:230,height:Math.max(54,text.height()+4),fill:"#fff3bf",stroke:item.id===selected?"#168dff":"#e6bb50",strokeWidth:item.id===selected?3:1.5,cornerRadius:7,shadowColor:"#63758a",shadowBlur:5,shadowOpacity:.16,shadowOffsetY:2}),text);group.on("dblclick dbltap",()=>{const value=window.prompt("Edit note",item.text??"");if(value!==null)commit(shapesRef.current.map(shape=>shape.id===item.id?{...shape,text:value}:shape));});node=group;}else if(item.type==="rectangle"){node=new Konva.Rect({x:item.x,y:item.y,width:item.width,height:item.height,fill:"#dff6f1",stroke:item.id===selected?"#168dff":"#159b8a",strokeWidth:item.id===selected?4:2.5,cornerRadius:10,draggable:true});}else{node=new Konva.Circle({x:item.x,y:item.y,radius:item.radius,fill:"#e0ecff",stroke:item.id===selected?"#168dff":"#4389dd",strokeWidth:item.id===selected?4:2.5,draggable:true});}node.on("click tap",()=>{setSelected(item.id);setTool("select");});if(item.type!=="pen")node.on("dragend",()=>commit(shapesRef.current.map(shape=>shape.id===item.id?{...shape,x:node.x(),y:node.y()}:shape)));canvas.add(node);}canvas.draw();},[shapes,selected]);
  // The white board is visual-only; pointer events must reach the Stage so the
  // active tool can create objects on an empty part of the canvas.
  useEffect(()=>{layer.current?.getChildren()[0]?.listening(false);},[shapes,selected]);
  function exportPng(){const uri=stage.current?.toDataURL({pixelRatio:2});if(!uri)return;const link=document.createElement("a");link.href=uri;link.download="shikshamesh-learning-canvas.png";link.click();}
  return <section className="canvas-workspace" aria-label="Shared learning canvas"><header className="canvas-topbar"><div><span className="canvas-kicker">SHARED CLASS WORKSPACE</span><h2>Learning Canvas</h2></div><div className="canvas-status"><span className="canvas-status-dot"/>{status||"Ready"}</div></header><div className="canvas-toolbar" role="toolbar" aria-label="Canvas tools">{tools.map(item=><button type="button" key={item.tool} className={tool===item.tool?"active":""} aria-pressed={tool===item.tool} onClick={()=>setTool(item.tool)}>{item.label}<kbd>{item.key}</kbd></button>)}<span className="canvas-toolbar-divider"/><button type="button" className="canvas-icon-button" disabled={!undoable} onClick={undo} aria-label="Undo">↶</button><button type="button" className="canvas-icon-button" disabled={!redoable} onClick={redo} aria-label="Redo">↷</button><button type="button" className="canvas-danger" onClick={()=>{if(window.confirm("Clear every object from the shared canvas?")){commit([]);setSelected(null);}}}>Clear</button><button type="button" className="canvas-export" onClick={exportPng}>Export PNG</button></div><div className="konva-shell"><div className="konva-viewport" style={{width:BOARD_W*zoom,height:BOARD_H*zoom}}><div ref={container}/></div></div><footer className="canvas-footer"><span><b>{tool==="select"?"Select and move":`${tools.find(item=>item.tool===tool)?.label} active`}</b> · Double-click a sticky note to edit · Press Delete to remove</span><div><button type="button" onClick={()=>setZoom(value=>Math.max(.5,Number((value-.1).toFixed(1))))}>−</button><span>{Math.round(zoom*100)}%</span><button type="button" onClick={()=>setZoom(value=>Math.min(1.5,Number((value+.1).toFixed(1))))}>+</button></div></footer></section>;
}
