"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { SignInPanel, useAuthSession } from "@/components/auth-session";
import { MasteryConsent } from "@/components/mastery-consent";

export default function AccountPage() {
  const { idToken, loading, changePassword, role, apiFetch, signOut } = useAuthSession();
  const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState("");
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [deletion, setDeletion] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); if (next !== confirm) return setError("New passwords do not match."); try { await changePassword(current, next); setCurrent(""); setNext(""); setConfirm(""); setMessage("Password changed successfully."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not change password"); } }
  async function requestDeletion() { if (!window.confirm("Submit an account-deletion request? Research consent will be withdrawn immediately.")) return; setDeletion("Submitting request…"); try { const response = await apiFetch("/api/account/deletion-request", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to submit deletion request"); setDeletion("Request recorded. You have been signed out."); window.setTimeout(signOut, 800); } catch (cause) { setDeletion(cause instanceof Error ? cause.message : "Unable to submit deletion request"); } }
  if (loading) return <main><p>Checking sign-in session…</p></main>;
  if (!idToken) return <main><section className="hero"><span className="eyebrow">ACCOUNT</span><h1>Sign in to manage your account.</h1></section><SignInPanel /></main>;
  const workspace = role === "teacher" || role === "admin" ? "/teacher" : "/";
  return <main className="account-page"><section className="account-hero"><div><span className="eyebrow">ACCOUNT SETTINGS</span><h1>Keep your account secure.</h1><p>Manage your sign-in password and optional data-training consent.</p></div><div className="account-role"><span>Signed in as</span><b>{role}</b><Link href={workspace}>Open workspace →</Link></div></section><div className="account-grid"><form className="account-card password-card" onSubmit={submit}><span className="eyebrow">SECURITY</span><h2>Change password</h2><p>Use a unique password with at least 8 characters.</p><label htmlFor="current-password">Current password</label><input id="current-password" type="password" autoComplete="current-password" value={current} onChange={event => setCurrent(event.target.value)} required /><label htmlFor="new-password">New password</label><input id="new-password" type="password" autoComplete="new-password" minLength={8} value={next} onChange={event => setNext(event.target.value)} required /><label htmlFor="confirm-password">Confirm new password</label><input id="confirm-password" type="password" autoComplete="new-password" minLength={8} value={confirm} onChange={event => setConfirm(event.target.value)} required /><button>Update password</button>{message && <p className="form-success">{message}</p>}{error && <p className="error">{error}</p>}</form><MasteryConsent /><section className="account-card danger-card"><span className="eyebrow">DATA CONTROL</span><h2>Request account deletion</h2><p>This immediately withdraws optional model-training consent and records a deletion request for your institution. Shared class material may be retained where another authorised teacher or student needs it.</p><button type="button" className="danger-button" onClick={() => void requestDeletion()}>Request deletion and sign out</button>{deletion && <p className="consent-status">{deletion}</p>}<Link className="privacy-link" href="/privacy">Read the privacy and retention summary →</Link></section></div></main>;
}
