"use client";

import { FormEvent, useRef, useState } from "react";
import { SignInPanel, useAuthSession } from "@/components/auth-session";

type Question = { id: string; prompt: string; sourceTitle: string };
type Session = { sessionId: string; questions: Question[]; provider: string };

export default function CourseInterviewPage() {
  const { apiFetch, idToken, loading: authLoading } = useAuthSession(); const recorderRef = useRef<any>(null); const [recordingQuestionId, setRecordingQuestionId] = useState<string | null>(null); const [history, setHistory] = useState<{ sessionId: string; focus: string; answered: number; averageScore: number }[]>([]);
  const [focus, setFocus] = useState("transport reliability"); const [session, setSession] = useState<Session | null>(null); const [answers, setAnswers] = useState<Record<string, string>>({}); const [feedback, setFeedback] = useState<Record<string, string>>({}); const [report, setReport] = useState<{ averageScore: number; answered: number; totalQuestions: number; feedback: string } | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function start(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await apiFetch("/api/interviews/course", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ classId: "cn-b", focus }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setSession(body); setAnswers({}); setFeedback({}); setReport(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not start interview"); } finally { setBusy(false); } }
  async function answer(questionId: string) { if (!session) return; setBusy(true); try { const response = await apiFetch(`/api/interviews/course/${session.sessionId}/answer`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ questionId, answer: answers[questionId] ?? "" }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setFeedback((current) => ({ ...current, [questionId]: `${body.score}% — ${body.feedback}` })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not score answer"); } finally { setBusy(false); } }
  async function loadReport() { if (!session) return; const response = await apiFetch(`/api/interviews/course/${session.sessionId}/report`); const body = await response.json(); if (response.ok) setReport(body); else setError(body.error); }
  async function loadHistory() { const response = await apiFetch("/api/interviews/course"); const body = await response.json(); if (response.ok) setHistory(body.interviews); else setError(body.error); }
  async function speak(text: string) { try { const response = await apiFetch("/api/interviews/speech/tts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ text }) }); if (!response.ok) throw new Error(); const url = URL.createObjectURL(await response.blob()); const audio = new Audio(url); audio.onended = () => URL.revokeObjectURL(url); await audio.play(); return; } catch { if (!("speechSynthesis" in window)) { setError("Text-to-speech is not supported by this browser."); return; } window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = "en-IN"; utterance.rate = 0.92; window.speechSynthesis.speak(utterance); } }
  function transcribe(questionId: string) { const Recognition = (window as any).SpeechRecognition ?? (window as any).webkitSpeechRecognition; if (!Recognition) { setError("Speech-to-text is not supported by this browser. Use Chrome/Edge or type your answer."); return; } const recognition = new Recognition(); recognition.lang = "en-IN"; recognition.interimResults = false; recognition.continuous = false; recognition.onresult = (event: any) => setAnswers((current) => ({ ...current, [questionId]: `${current[questionId] ?? ""} ${event.results[0][0].transcript}`.trim() })); recognition.onerror = () => setError("Speech recognition could not understand the response. Please try again or type your answer."); recognition.start(); }
  async function recordAnswer(questionId: string) { if (recorderRef.current) { recorderRef.current.stop(); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const recorder = new MediaRecorder(stream); const chunks: Blob[] = []; recorderRef.current = recorder; setRecordingQuestionId(questionId); recorder.ondataavailable = (event) => chunks.push(event.data); recorder.onstop = async () => { recorderRef.current = null; setRecordingQuestionId(null); stream.getTracks().forEach((track) => track.stop()); try { const audio = new Blob(chunks, { type: recorder.mimeType || "audio/webm" }); const response = await apiFetch("/api/interviews/speech/stt", { method: "POST", headers: { "content-type": audio.type }, body: audio }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setAnswers((current) => ({ ...current, [questionId]: `${current[questionId] ?? ""} ${body.transcript}`.trim() })); } catch { transcribe(questionId); } }; recorder.start(); } catch { transcribe(questionId); } }
  if (authLoading) return <main><p>Checking sign-in session…</p></main>;
  if (!idToken) return <main><section className="hero"><span className="eyebrow">COURSE INTERVIEW AGENT</span><h1>Practice from your own notes.</h1></section><SignInPanel /></main>;
  return <main><section className="hero"><span className="eyebrow">COURSE INTERVIEW AGENT</span><h1>Interview practice grounded in uploaded notes.</h1><p>The agent retrieves only your authorized class material, asks note-based questions, and gives feedback on your answer.</p></section><SignInPanel /><form className="composer" onSubmit={start}><label>Topic or concept from your notes</label><input value={focus} onChange={(event) => setFocus(event.target.value)} required /><button disabled={busy}>{busy ? "Preparing…" : "Start course interview"}</button> <button type="button" onClick={loadHistory}>Previous interviews</button></form>{history.length > 0 && <section className="result"><h2>Interview history</h2>{history.map((item) => <p key={item.sessionId}><b>{item.focus}</b> — {item.answered} answers · {item.averageScore}% average</p>)}</section>}{error && <p className="error">{error}</p>}{session && <section className="result"><p><small>Course retrieval: {session.provider} · ElevenLabs/Deepgram are used when configured, otherwise browser speech is used.</small></p>{session.questions.map((question, index) => <article className="assessment" key={question.id}><h2>{index + 1}. {question.prompt}</h2><small>Source: {question.sourceTitle}</small><p><button type="button" onClick={() => speak(question.prompt)}>🔊 Read question</button> <button type="button" onClick={() => recordAnswer(question.id)}>🎙️ {recordingQuestionId === question.id ? "Stop recording" : "Record answer"}</button></p><textarea value={answers[question.id] ?? ""} onChange={(event) => setAnswers((current) => ({ ...current, [question.id]: event.target.value }))} placeholder="Answer in your own words, or record your answer…" /><button disabled={busy || !answers[question.id]?.trim()} onClick={() => answer(question.id)} type="button">Get feedback</button>{feedback[question.id] && <p className="score">{feedback[question.id]}</p>}</article>)}<button onClick={loadReport} type="button">View interview report</button>{report && <p className="score">Average: {report.averageScore}% · Answered {report.answered}/{report.totalQuestions}. {report.feedback}</p>}</section>}</main>;
}
