"use client";
import { DEMO_TOPIC, DEMO_AGENDA } from "@/lib/demo-content";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { io, type Socket } from "socket.io-client";
import { SignInPanel, useAuthSession } from "@/components/auth-session";
import { MarkdownAnswer } from "@/components/markdown-answer";
import { IvsRoom } from "@/components/ivs-room";
type Message={id:string;senderRole:string;text:string;createdAt:string;attachment?:{type:string;objectId:string}};
type Participant={id:string;displayName:string;role:"student"|"teacher"|"admin"};
type Lesson={id:string;title:string;scheduledFor?:string;durationMinutes?:number;status:string;agenda:string[];teacherName:string};
const fallback:Lesson={id:"cn-b-live",title:DEMO_TOPIC + " Lab",durationMinutes:45,status:"live",teacherName:"Teacher",agenda:DEMO_AGENDA};

export default function LivePage(){
  const {idToken,role,loading,apiFetch}=useAuthSession();const socket=useRef<Socket|null>(null);
  const [lessons,setLessons]=useState<Lesson[]>([]),[lessonId,setLessonId]=useState(""),[lessonStatus,setLessonStatus]=useState("Loading scheduled lessons…"),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[online,setOnline]=useState(0),[participants,setParticipants]=useState<Participant[]>([]),[hands,setHands]=useState(0),[raised,setRaised]=useState(false),[attachment,setAttachment]=useState("canvas:workspace-1"),[status,setStatus]=useState("Connecting…"),[tab,setTab]=useState<"discussion"|"people">("discussion");
  const teacher=role==="teacher"||role==="admin";const lesson=useMemo(()=>lessons.find(item=>item.id===lessonId)??lessons[0]??fallback,[lessons,lessonId]);const roomId=lesson.id;const topic=lesson.title;
  useEffect(()=>{if(!idToken)return;void apiFetch("/api/teacher/live-lessons?classId=cn-b").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error??"Could not load lessons");const next=body.lessons as Lesson[];setLessons(next);setLessonId(current=>current||next.find(item=>item.status==="live")?.id||next[0]?.id||"");setLessonStatus(next.length?"Choose the lesson you want to join.":"No scheduled lesson yet — showing the sample room.");}).catch(reason=>setLessonStatus(reason instanceof Error?reason.message:"Could not load scheduled lessons"));},[apiFetch,idToken]);
  useEffect(()=>{if(!idToken)return;const client=io(process.env.NEXT_PUBLIC_REALTIME_URL??"http://localhost:3003",{auth:{token:idToken},reconnectionAttempts:3,timeout:5000});socket.current=client;client.on("connect",()=>{setStatus("Live and connected");client.emit("room:join",{roomId,classId:"cn-b"});});client.on("connect_error",(error:Error)=>setStatus(`Realtime connection rejected: ${error.message||"unknown error"}`));client.on("room:error",setStatus);client.on("room:removed",(message:string)=>{setStatus(message);client.disconnect();});client.on("presence:update",({onlineCount,participants:next}:{onlineCount:number;participants:Participant[]})=>{setOnline(onlineCount);setParticipants(next);});client.on("hand:update",({raised:nextRaised}:{raised:boolean})=>setHands(count=>Math.max(0,count+(nextRaised?1:-1))));client.on("chat:history",(history:Message[])=>setMessages(history));client.on("chat:message",(message:Message)=>setMessages(current=>[...current,message]));return()=>{client.disconnect();};},[idToken,roomId]);
  async function send(event:FormEvent){event.preventDefault();if(!text.trim())return;const outgoing=text.trim();const[type,objectId]=attachment.split(":");socket.current?.emit("chat:message",{roomId,classId:"cn-b",text:outgoing,attachment:objectId?{type,objectId}:undefined});setText("");if(outgoing.toLowerCase().startsWith("@shikshamesh")){setStatus("ShikshaMesh is reasoning…");const response=await apiFetch("/api/orchestrate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query:`Live classroom lesson: ${topic}. Question with ${type} object ${objectId}: ${outgoing.replace(/^@shikshamesh\s*/i,"")}`})});const body=await response.json();setMessages(current=>[...current,{id:crypto.randomUUID(),senderRole:"ShikshaMesh",text:response.ok?body.answer:body.error,createdAt:new Date().toISOString(),attachment:objectId?{type,objectId}:undefined}]);setStatus(socket.current?.connected?"Live and connected":"Realtime server is offline — start npm run realtime");}}
  function remove(participantId:string){socket.current?.emit("moderation:remove",{roomId,classId:"cn-b",participantId});}
  function publish(type:"canvas"|"diagram"){const objectId=type==="canvas"?`lesson-${lesson.id}`:`diagram-${lesson.id}`;socket.current?.emit("chat:message",{roomId,classId:"cn-b",text:`Teacher published the ${type} for ${topic}. Open it from the lesson resources.`,attachment:{type,objectId}});setTab("discussion");}
  if(loading)return <main><p>Checking sign-in session…</p></main>;if(!idToken)return <main><section className="hero"><h1>Live Classroom</h1></section><SignInPanel/></main>;
  const encodedTopic=`${encodeURIComponent(topic)}&workspace=${encodeURIComponent(lesson.id)}`;
  return <main className="live-page"><section className="live-heading"><div><span className="eyebrow">SHIKSHAMESH LIVE CLASSROOM</span><h1>{lesson.title}</h1><p><span className={socket.current?.connected?"live-dot connected":"live-dot"}/>{status}</p></div><div className="live-actions"><button onClick={()=>{const next=!raised;setRaised(next);socket.current?.emit("hand:raise",{roomId,classId:"cn-b",raised:next});}}>{raised?"Lower hand":"Raise hand"}</button><a href={`/canvas?topic=${encodedTopic}`}>Open shared canvas</a></div></section>
    <section className="lesson-picker"><div><span className="eyebrow">CLASS SCHEDULE</span><b>{lessonStatus}</b></div>{lessons.length>0&&<label>Active lesson<select value={lesson.id} onChange={event=>{setLessonId(event.target.value);setMessages([]);setHands(0);setRaised(false);}}>{lessons.map(item=><option key={item.id} value={item.id}>{item.title} · {item.status}</option>)}</select></label>}</section>
    <div className="classroom-grid"><section className="lesson-stage"><div className="stage-top"><span className="stage-live">{lesson.status.toUpperCase()} LESSON</span><span>CN-B · {lesson.durationMinutes??45} minutes</span></div><div className="lesson-board"><p className="eyebrow">TODAY’S LEARNING FOCUS</p><h2>{lesson.title}</h2><p>{lesson.agenda[0]??"Open the Canvas to work through this topic together."}</p><div className="code-preview"><code>Open the shared Canvas or Diagram Studio to map this concept step by step.</code></div><div className="lesson-resource-links"><a href={`/diagrams?topic=${encodedTopic}`}>Create a diagram →</a><a href={`/notes?topic=${encodedTopic}`}>Open smart notes →</a><a href={`/interview?topic=${encodedTopic}`}>Practice interview →</a></div></div><div className="stage-footer"><span>{online} participant(s)</span><span>{hands} hand(s) raised</span><span>{lesson.teacherName} · class workspace ready</span></div></section>
      <aside className="class-sidebar"><div className="sidebar-tabs"><button className={tab==="discussion"?"active":""} onClick={()=>setTab("discussion")}>Discussion</button><button className={tab==="people"?"active":""} onClick={()=>setTab("people")}>People ({online})</button></div>{tab==="people"?<div className="people-list">{participants.length===0?<p className="empty-chat">No one else is connected yet.</p>:participants.map(participant=><p key={participant.id}><b>{participant.displayName}</b><br/><small>{participant.role==="teacher"||participant.role==="admin"?"Teacher / host":"Student"}</small>{teacher&&participant.role==="student"&&<button className="moderate-button" type="button" onClick={()=>remove(participant.id)}>Remove</button>}</p>)}<p><b>ShikshaMesh</b><br/><small>Available for note-grounded help</small></p></div>:<><div className="chat-feed">{messages.length===0?<p className="empty-chat">Ask a question about {topic}, share a Canvas object, or type <b>@ShikshaMesh</b> for a note-grounded explanation.</p>:messages.map(message=><article key={message.id} className="chat-message"><b>{message.senderRole}</b>{message.senderRole==="ShikshaMesh"?<MarkdownAnswer text={message.text}/>:<p>{message.text}</p>}{message.attachment&&<small>Linked {message.attachment.type}: {message.attachment.objectId}</small>}</article>)}</div><form className="live-compose" onSubmit={send}><input value={text} onChange={event=>setText(event.target.value)} placeholder={`Ask about ${topic} or @ShikshaMesh…`}/><select value={attachment} onChange={event=>setAttachment(event.target.value)}><option value="canvas:workspace-1">Link Canvas workspace</option><option value="geometry:triangle-1">Link geometry object</option><option value="code:snippet-1">Link code snippet</option></select><button>Send</button></form></>}</aside></div>
    {teacher&&<section className="teacher-presenter"><div><span className="eyebrow">TEACHER PRESENTATION CONTROLS</span><h2>Share the lesson workspace.</h2><p>Publish a resource into this lesson’s persistent discussion. Students receive it in real time.</p></div><div><button type="button" onClick={()=>publish("canvas")}>Publish shared Canvas</button><button type="button" className="secondary-action" onClick={()=>publish("diagram")}>Publish Diagram Studio</button></div></section>}<IvsRoom/><section className="agenda-card"><span className="eyebrow">CLASS FLOW</span><h2>{lesson.title}</h2><ol>{lesson.agenda.map(item=><li key={item}>{item}</li>)}</ol><p><small>Teacher lessons are stored in PostgreSQL. Chat, attendance, Canvas, diagrams, and optional IVS video all use the selected lesson’s room.</small></p></section></main>;
}
