"use client";
import { useEffect, useState } from "react";
import { SignInPanel, useAuthSession } from "@/components/auth-session";
type Quiz = { id: string; title: string }; type Question = { id: string; prompt: string; options: string[]; topic: string }; type ActiveQuiz = { id: string; title: string; questions: Question[] };
export default function QuizzesPage() { const { idToken, apiFetch, loading } = useAuthSession(); const [quizzes, setQuizzes] = useState<Quiz[]>([]); const [quiz, setQuiz] = useState<ActiveQuiz | null>(null); const [answers, setAnswers] = useState<Record<string, number>>({}); const [message, setMessage] = useState("");
  useEffect(() => { if (idToken) void apiFetch("/api/quizzes?classId=cn-b").then((r) => r.json()).then((b) => setQuizzes(b.quizzes ?? [])); }, [apiFetch, idToken]);
  async function open(id: string) { const r = await apiFetch(`/api/quizzes/${id}`); const body = await r.json(); if (!r.ok) return setMessage(body.error); setQuiz(body); setAnswers({}); }
  async function submit() { if (!quiz) return; const r = await apiFetch(`/api/quizzes/${quiz.id}/submit`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ answers: Object.entries(answers).map(([questionId, selectedOption]) => ({ questionId, selectedOption })) }) }); const body = await r.json(); const topic = quiz.questions[0]?.topic; const mastery = topic ? body.mastery?.mastery?.[topic] : undefined; setMessage(r.ok ? `Submitted: ${body.score}% (${body.correct}/${body.attempted})${typeof mastery === "number" ? ` · Mastery updated to ${Math.round(mastery * 100)}%` : ""}` : body.error); }
  if (loading) return <main><p>Checking sign-in session…</p></main>; if (!idToken) return <main><section className="hero"><h1>Quiz practice</h1></section><SignInPanel /></main>;
  return <main><section className="hero"><span className="eyebrow">ADAPTIVE QUIZZES</span><h1>Practice, learn, adapt.</h1><a href="/">Back to ShikshaMesh Core</a></section>{!quiz ? <section className="result"><h2>Published quizzes</h2>{quizzes.length ? quizzes.map((item) => <p key={item.id}><button onClick={() => void open(item.id)}>{item.title}</button></p>) : <p>No published quizzes yet.</p>}</section> : <section className="result"><h2>{quiz.title}</h2>{quiz.questions.map((q, i) => <fieldset className="assessment" key={q.id}><legend>{i + 1}. {q.prompt}</legend>{q.options.map((option, index) => <label className="option" key={option}><input type="radio" name={q.id} onChange={() => setAnswers((a) => ({ ...a, [q.id]: index }))} />{option}</label>)}</fieldset>)}<button disabled={Object.keys(answers).length !== quiz.questions.length} onClick={() => void submit()}>Submit quiz</button></section>}{message && <p className="score">{message}</p>}</main>; }
