"use client";
import { DEMO_TOPIC, DEMO_AGENDA } from "@/lib/demo-content";
import { FormEvent, useEffect, useState } from "react";
import { SignInPanel, useAuthSession } from "@/components/auth-session";

type Lesson = { id:string; title:string; scheduledFor?:string; durationMinutes?:number; status:string; agenda:string[]; teacherName:string };
function defaultTime() { const value=new Date(Date.now()+30*60*1000); value.setSeconds(0,0); return value.toISOString().slice(0,16); }

export default function TeacherLivePage() {
  const { idToken, role, loading, apiFetch } = useAuthSession(); const [title,setTitle]=useState(DEMO_TOPIC + " Lab"), [scheduledFor,setScheduledFor]=useState(defaultTime()), [duration,setDuration]=useState(45), [agenda,setAgenda]=useState(DEMO_AGENDA.join("\n")), [lessons,setLessons]=useState<Lesson[]>([]), [error,setError]=useState(""), [saving,setSaving]=useState(false);
  async function load(){const response=await apiFetch("/api/teacher/live-lessons?classId=cn-b");const body=await response.json();if(response.ok)setLessons(body.lessons);else setError(body.error??"Unable to load lessons");}
  useEffect(()=>{if(idToken&&(role==="teacher"||role==="admin"))void load();},[idToken,role]);
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await apiFetch("/api/teacher/live-lessons",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({classId:"cn-b",title,scheduledFor:new Date(scheduledFor).toISOString(),durationMinutes:duration,agenda:agenda.split("\n").map((item)=>item.trim()).filter(Boolean)})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Unable to schedule lesson");setLessons((current)=>[body,...current]);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to schedule lesson");}finally{setSaving(false);}}
  if(loading)return <main><p>Checking sign-in session…</p></main>; if(!idToken)return <main><section className="hero"><h1>Live lesson scheduling</h1></section><SignInPanel/></main>; if(role!=="teacher"&&role!=="admin")return <main><section className="hero"><h1>Teacher access required</h1><p>Only teachers and administrators can schedule live lessons.</p></section></main>;
  return <main><section className="hero"><span className="eyebrow">TEACHER LIVE CLASSROOM</span><h1>Schedule a live learning room.</h1><p>Create a structured lesson with agenda items. Students can then join the Live Class and shared Canvas.</p></section><form className="composer teacher-form" onSubmit={submit}><label htmlFor="lesson-title">Lesson title</label><input id="lesson-title" value={title} onChange={(event)=>setTitle(event.target.value)}/><label htmlFor="lesson-time">Starts at</label><input id="lesson-time" type="datetime-local" value={scheduledFor} onChange={(event)=>setScheduledFor(event.target.value)}/><label htmlFor="lesson-duration">Duration in minutes</label><input id="lesson-duration" type="number" min={5} max={240} value={duration} onChange={(event)=>setDuration(Number(event.target.value))}/><label htmlFor="lesson-agenda">Agenda — one item per line</label><textarea id="lesson-agenda" rows={5} value={agenda} onChange={(event)=>setAgenda(event.target.value)}/><button disabled={saving}>{saving?"Scheduling…":"Schedule live lesson"}</button></form>{error&&<p className="error">{error}</p>}<section className="result"><span className="eyebrow">CN-B SCHEDULE</span><h2>Upcoming and recent lessons</h2>{lessons.length===0?<p>No lessons scheduled yet.</p>:<div className="lesson-list">{lessons.map((lesson)=><article key={lesson.id}><b>{lesson.title}</b><small>{lesson.scheduledFor?new Date(lesson.scheduledFor).toLocaleString():"No scheduled time"} · {lesson.durationMinutes??45} minutes · {lesson.status}</small><p>{lesson.agenda.join(" · ")}</p></article>)}</div>}</section></main>;
}
