"use client";
import { useEffect, useRef } from "react";
type Shape = "circle" | "triangle" | "square";
type Props = { cellSize?: number; influenceRadiusVmin?: number; idleScale?: number; minPeakScale?: number; maxPeakScale?: number; shapes?: Shape[]; opacity?: number };
export function ShapesDots({ cellSize = 40, influenceRadiusVmin = 25, idleScale = .1, minPeakScale = 1, maxPeakScale = 3, shapes = ["circle", "triangle", "square"], opacity = 1 }: Props) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => { const canvas = ref.current; const context = canvas?.getContext("2d"); if (!canvas || !context) return; let frame = 0; let pointer = { x: -1000, y: -1000 }; const draw = () => { const box = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio, 2), radius = Math.min(box.width, box.height) * influenceRadiusVmin / 100; canvas.width = Math.floor(box.width * dpr); canvas.height = Math.floor(box.height * dpr); context.setTransform(dpr, 0, 0, dpr, 0, 0); context.clearRect(0, 0, box.width, box.height); for (let y = cellSize / 2; y < box.height; y += cellSize) for (let x = cellSize / 2; x < box.width; x += cellSize) { const impact = Math.max(0, 1 - Math.hypot(x - pointer.x, y - pointer.y) / radius), scale = idleScale + impact * (minPeakScale + (maxPeakScale - minPeakScale) * .35), shape = shapes[(Math.floor(x / cellSize) + Math.floor(y / cellSize)) % shapes.length]; context.save(); context.translate(x, y); context.scale(scale, scale); context.fillStyle = `rgba(255,255,255,${(0.16 + impact * .72) * opacity})`; context.beginPath(); if (shape === "circle") context.arc(0, 0, 2.4, 0, Math.PI * 2); else if (shape === "square") context.rect(-2.1, -2.1, 4.2, 4.2); else { context.moveTo(0, -3); context.lineTo(2.7, 2.2); context.lineTo(-2.7, 2.2); context.closePath(); } context.fill(); context.restore(); } frame = requestAnimationFrame(draw); }; const move = (event: PointerEvent) => { const box = canvas.getBoundingClientRect(); pointer = { x: event.clientX - box.left, y: event.clientY - box.top }; }; const leave = () => { pointer = { x: -1000, y: -1000 }; }; window.addEventListener("pointermove", move); canvas.addEventListener("pointerleave", leave); const observer = new ResizeObserver(() => { cancelAnimationFrame(frame); draw(); }); observer.observe(canvas); draw(); return () => { cancelAnimationFrame(frame); observer.disconnect(); window.removeEventListener("pointermove", move); canvas.removeEventListener("pointerleave", leave); }; }, [cellSize, influenceRadiusVmin, idleScale, minPeakScale, maxPeakScale, opacity, shapes]);
  return <canvas ref={ref} aria-hidden="true" className="shapes-dots" />;
}
